detector:
  harris:
    blocksize: 5
    ksize: 5
    k: 0.04
    threshold: 0.005

stereo_vo:
  disparity:
    num_disp: 50
    min_disp: 0
    block_size: 10

plot:
  view: [-55, 145, -60]
  ylim: [0.0, 1.0]
